### ISSUE TITLE
Unwanted fade out & track change

### ISSUE THREAD

**Issue by TakuikaNinja** [nununoisy/nsf-presenter-rs#10]
An unwanted fadeout and track change occurs in these scenarios:
1. The track is over 3 minutes long (looped or not). A fade out occurs before the 3 minute mark, then the next track plays for the rest of the duration including the fade out.
2.  The track does not loop and ends within the specified duration. The next track plays for the rest of the duration including the fade out.

**Comment by TakuikaNinja** [comment]
Regarding the "maximum" duration of 3 minutes, it would be nice if there was an option to change this in case the song length is unknown (or technically infinite due to channel desyncs and such) but longer than 3 minutes.

**Comment by nununoisy** [comment]
I went ahead and investigated this, and found out that this bug is ancient - it was probably in the very first version of NSFPresenter and just hasn't been caught until now. The reason is that RusticNES' NSF player defaults to playing a song for 3 minutes but only if the NSF has multiple tracks. Most people (myself included) only use NSFPresenter for single track NSFs since that covers the vast majority of typical tracker exports, so the bug hasn't been triggered until now.

The fix for this is thankfully pretty simple (one line of code!) but I don't want to create a release just for this fix - I have a few extra features I'd like to finish first. With that said, I know you compiled from source, so I went ahead and pushed a commit to fix this so you can get a proper render done. I'll leave this issue open for now to make sure I test before the next release.

**Comment by nununoisy** [comment]
Fixed in v0.6.0.
