### ISSUE TITLE
[Suggestion] An option to hide channels

### ISSUE THREAD

**Issue by TheDuccinator** [nununoisy/nsf-presenter-rs#2]
Add the option to hide channels which is not in use. Some .nsfs uses the expansion channels only or use a few channels of a chip.

**Comment by nununoisy** [comment]
This is something that's been on my todos for a while since I also have some modules that don't use certain channels.

AFAIK this is already supported by RusticNES, I just need to find a good way to expose the functionality in the CLI/GUI frontends. Depending on the complexity of the frontend setup, I might be able to add some additional configuration (scaling, colors, etc.).

**Comment by TheDuccinator** [comment]
Ah gotcha.

**Comment by nununoisy** [comment]
Added in v0.4.0.
