### ISSUE TITLE
Crashes 

### ISSUE THREAD

**Issue by MusicBoiJBoy** [nununoisy/nsf-presenter-rs#3]
as soon as i open the application it crashes and idk why

**Comment by nununoisy** [comment]
Sorry to hear that. I’m going to need a bit more information to help you out.

- What OS are you using?
- What are the specs of your machine (doesn’t need to be too detailed)?
- Do you get any sort of error when the crash occurs, like a missing DLL? Or is it a console window that closes immediately?

**Comment by MusicBoiJBoy** [comment]
i am using windows 10.

i am using an Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz processor 

and no i didnt get a message saying that one of the DLL's are missong

**Comment by nununoisy** [comment]
It’s just a hunch, but since I compiled on a more modern processor, it’s entirely possible that the build I posted is using processor extensions that your CPU doesn’t support. I’ll rebuild the release using a compatible instruction set when I get home - hopefully that fixes it.
If it doesn’t, I have an Ivy Bridge system with similar specs that I can use to test on my end.

**Comment by nununoisy** [comment]
Alright, I've updated the release with binaries compiled using `-Ctarget-cpu=x86-64-v2` which should include support for your processor. Try running it now, and if still isn't working let me know.
